version: 2.1
jobs:
  test-go:
    # Install go modules and run tests
    docker:
      - image: cimg/go:1.22
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: go mod download
      - run:
          name: Run tests
          command: go test ./...

  build-and-push-image:
    docker:
      - image: mirdsmulya/aws-docker # This is a custom image that contains aws-cli and docker
    environment:
      DOCKER_DRIVER: overlay2
      AWS_DEFAULT_REGION: "ap-southeast-1"
      ECR_REGISTRY: "675327529402.dkr.ecr.ap-southeast-1.amazonaws.com"
      ECR_REPOSITORY: "fast-campus"
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Login to ECR
          command: |
            echo $(aws ecr get-login-password --region $AWS_DEFAULT_REGION) | docker login --username AWS --password-stdin $ECR_REGISTRY
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${CIRCLE_TAG} .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:${CIRCLE_TAG}

  deploy-to-eks:
    docker:
      - image: mirdsmulya/aws-helm # This is a custom image that contains aws-cli and helm
    environment:
      AWS_DEFAULT_REGION: "ap-southeast-1"
      EKS_CLUSTER_NAME: "fast-campus-cluster"
      KUBERNETES_NAMESPACE: "app"
      HELM_CHART_PATH: "deployment/k8s"
      HELM_CHART_NAME: "hello-world"
    steps:
      - checkout
      - run:
          name: Update kubeconfig
          command: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION
      - run:
          name: Deploy to EKS using Helm
          command: |
            helm upgrade --install $HELM_CHART_NAME $HELM_CHART_PATH -f $HELM_CHART_PATH/values.yaml --namespace $KUBERNETES_NAMESPACE --set image.tag=${CIRCLE_TAG}

workflows:
  CI-CD-EKS:
    jobs:
      - test-go
      - build-and-push-image:
          requires:
            - test-go
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/ # Only run this job when a tag is pushed via git tag -a v0.1.0 -m "Release v0.1.0"
      - deploy-to-eks:
          requires:
            - build-and-push-image
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/ # Only run this job when a tag is pushed via git tag -a v0.1.0 -m "Release v0.1.0"
